/* eslint-disable no-undef */
import React from 'react';
import ReactDOM from 'react-dom';
import { shallow } from 'enzyme';
import toJson from 'enzyme-to-json';
import { BrowserRouter } from 'react-router-dom';
import ChordDisplay from './ChordDisplay';

const testProgression = 'i-v-vi-v';

const chordTestArray = [
  {
    id: 3,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'C major',
    notation: 'C',
    variation: '1',
    chord_code: '0,x,2,1,o,0,o',
    tag: 'basic, beginner, open',
  },
  {
    id: 7,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'G major',
    notation: 'G',
    variation: '1',
    chord_code: '0,2,1,o,o,2,2',
    tag: 'basic, beginner, open',
  },
  {
    id: 8,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'A minor',
    notation: 'Am',
    variation: '1',
    chord_code: '0,x,o,1,1,0,o',
    tag: 'basic, beginner, open',
  },
  {
    id: 37,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'A minor 7 sus4',
    notation: 'Am',
    variation: '2',
    chord_code: '0,x,o,1,o,2,2',
    tag: 'jazz, open, seventh',
  },
  {
    id: 39,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'C major add9',
    notation: 'C',
    variation: '2',
    chord_code: '0,x,2,1,o,2,2',
    tag: 'jazz, open',
  },
  {
    id: 40,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'C major 7',
    notation: 'C',
    variation: '3',
    chord_code: '3,x,0,2,o,o,o',
    tag: 'dissonant, open, seventh',
  },
  {
    id: 43,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'G major',
    notation: 'G',
    variation: '3',
    chord_code: '10,x,x,2,o,2,o',
    tag: 'intermediate',
  },
  {
    id: 44,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'C major 7',
    notation: 'C',
    variation: '4',
    chord_code: '8,0,2,1,1,0,0,b',
    tag: 'intermediate, seventh',
  },
  {
    id: 46,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'G major 7',
    notation: 'G',
    variation: '4',
    chord_code: '0,2,1,o,o,o,0',
    tag: 'intermediate, seventh',
  },
  {
    id: 52,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'G major/D',
    notation: 'G',
    variation: '5',
    chord_code: '7,x,x,o,0,1,0',
    tag: 'intermediate',
  },
  {
    id: 53,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'A minor 9',
    notation: 'Am',
    variation: '3',
    chord_code: '5,x,o,0,0,0,2,b',
    tag: 'intermediate, jazz, mellow',
  },
  {
    id: 58,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'G5',
    notation: 'G',
    variation: '6',
    chord_code: '3,0,2,2,x,x,x',
    tag: 'basic, rock, blues, power chord',
  },
  {
    id: 59,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'C5',
    notation: 'C',
    variation: '5',
    chord_code: '3,0,2,2,x,x,x',
    tag: 'basic, rock, blues, power chord',
  },
  {
    id: 65,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'Cadd9',
    notation: 'C',
    variation: '6',
    chord_code: '0,o,2,x,o,2,o',
    tag: 'intermediate, rock, blues',
  },
  {
    id: 69,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'GMaj7 add#11',
    notation: 'G',
    variation: '7',
    chord_code: '3,0,2,1,3,o,x',
    tag: 'advanced, seventh',
  },
  {
    id: 70,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'Amin#6 add9',
    notation: 'Am',
    variation: '4',
    chord_code: '4,x,o,0,1,1,3',
    tag: 'advanced',
  },
  {
    id: 74,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'CMaj7/G',
    notation: 'C',
    variation: '7',
    chord_code: '0,2,2,1,o,o,o',
    tag: 'intermediate, seventh',
  },
  {
    id: 75,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'G5 add9',
    notation: 'G',
    variation: '8',
    chord_code: '0,2,x,o,1,2,2',
    tag: 'intermediate, power chord',
  },
  {
    id: 77,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'Amin7/E',
    notation: 'Am',
    variation: '5',
    chord_code: '12,0,0,2,o,1,3',
    tag: 'advanced, seventh',
  },
  {
    id: 83,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'Amin6',
    notation: 'Am',
    variation: '6',
    chord_code: '5,x,o,0,1,1,o',
    tag: 'intermediate',
  },
  {
    id: 86,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'A minor',
    notation: 'Am',
    variation: '7',
    chord_code: '9,x,o,o,1,2,0',
    tag: 'intermediate',
  },
  {
    id: 92,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'GMaj7/B',
    notation: 'G',
    variation: '9',
    chord_code: '7,0,3,2,0,0,0,b',
    tag: 'advanced, seventh',
  },
  {
    id: 93,
    tonic: 'C',
    second: 'Dm',
    third: 'Em',
    fourth: 'F',
    fifth: 'G',
    sixth: 'Am',
    seventh: 'Bdim',
    chord_name: 'Amin/Maj7',
    notation: 'Am',
    variation: '8',
    chord_code: '5,x,o,1,0,0,o',
    tag: 'advanced, seventh, jazz',
  },
];

describe('ChordDisplay component', () => {
  it('renders without crashing', () => {
    const div = document.createElement('div');
    ReactDOM.render(
      <BrowserRouter>
        <ChordDisplay chords={chordTestArray} progression={testProgression} />
      </BrowserRouter>,
      div,
    );
    ReactDOM.unmountComponentAtNode(div);
  });
  it('renders the display correctly', () => {
    const wrapper = shallow(<ChordDisplay chords={chordTestArray} progression={testProgression} />);
    expect(toJson(wrapper)).toMatchSnapshot();
  });
});
